server:
  port: 8080

spring:
  application:
    name: agent-portal-service

# External API configurations
api:
  origami:
    base-url: https://api.origami.com
    api-key: ${ORIGAMI_API_KEY:your-origami-api-key}
  rootsai:
    base-url: https://api.roots.ai
    api-key: ${ROOTSAI_API_KEY:your-rootsai-api-key}
  agent-portal:
    base-url: https://agent-portal.windsurf.com
    api-key: ${AGENT_PORTAL_API_KEY:your-agent-portal-api-key}

# Security Configuration
security:
  api-key: ${API_KEY:your-secure-api-key}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.windsurf.agentportal: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: DEBUG

# OpenFeign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
